- README.md
> update the readme file 

- components/common/src/assets/css/components/dutyTable.less
- components/common/src/assets/css/index.less
- components/common/src/components/nv-dutytable/CONSTANTS.js
- components/common/src/components/nv-dutytable/date-picker.js
- components/common/src/components/nv-dutytable/dutyTable.vue
- components/common/src/components/nv-dutytable/index.js
- components/common/src/index.js
- components/common/test/unit/specs/nvDutyTable.spec.js
Add the duty-table component, the front end can display the duty function independently, and can also rely on the back end to implement alarm notification and other functions.
> add dutyTable components

- doc/src/common/header.js
- doc/src/common/router.js
- doc/src/doc/component/dutyTable/dutyTable.md
- doc/src/example/dutyTable/nvDutyTableComplexDemo.vue
- doc/src/example/dutyTable/nvDutyTableNormalDemo.vue
Supplemental dutyTable documentation, and examples of use
> add dutyTable doc

- components/visual/demo/app.vue
- components/visual/demo/components/bubble.vue
- components/visual/demo/router.js
- components/visual/src/index.js
- components/visual/src/mdbubble/CONSTANTS.js
- components/visual/src/mdbubble/mdbubble.vue
- components/visual/src/mdbubble/mdbubbleCore.vue
- components/visual/src/util/util.js
- components/visual/test/unit/index.js
- components/visual/test/unit/specs/nvBubble.spec.js
Increase the scatter plot, which can be used as a room room connectivity display
> add bubble

- components/common/CHANGELOG.md
- components/common/demo/components/tree/tree.vue
- components/common/package.json
- components/common/src/components/nv-datepicker/commonTimePanel.vue
- components/common/src/components/nv-datepicker/consoleTimePanel.vue
- components/common/src/components/nv-datepicker/datePicker.vue
- components/common/src/components/nv-datepicker/timePanel.vue
- components/common/src/components/nv-tree/node.vue
- components/common/src/components/nv-tree/tree.js
> Submit for update NvDatePicker component

- components/common/CHANGELOG.md
- components/common/package.json
- components/common/src/components/nv-textline/textLine.vue
Update for fix textline style error in firefox
> Update for fix textline style error in firefox

- components/common/src/components/nv-chart/chartUtil.js
- components/common/src/components/nv-chart/trend.vue
add trendData and seriesFilter
> add trendData and seriesFilter

- components/common/package.json
- packages/noahv-request/package.json
update noahv-request version:1.0.3
> update noahv-request version:1.0.3

- components/common/CHANGELOG.md
- components/common/demo/app.vue
- components/common/demo/components/checkbox/checkbox.vue
- components/common/demo/components/pipline/pipline.less
- components/common/demo/components/pipline/pipline.vue
- components/common/demo/components/transfer/transfer.less
- components/common/demo/components/transfer/transfer.vue
- components/common/demo/router.js
- components/common/package.json
- components/common/src/assets/css/components/checkbox.less
- components/common/src/assets/css/components/pipline.less
- components/common/src/assets/css/components/pool.less
- components/common/src/assets/css/components/transfer.less
- components/common/src/assets/css/index.less
- components/common/src/components/nv-checkbox/checkbox.vue
- components/common/src/components/nv-checkbox/index.js
- components/common/src/components/nv-pipline/index.js
- components/common/src/components/nv-pipline/pipline.vue
- components/common/src/components/nv-transfer/index.js
- components/common/src/components/nv-transfer/pool.vue
- components/common/src/components/nv-transfer/transfer.vue
- components/common/src/index.js
- components/common/test/unit/specs/nvPipline.spec.js
- components/common/test/unit/specs/nvTransfer.spec.js
> add NvPipline and NvTransfer for NoahV Components

- doc/src/example/header/complex.vue
- doc/src/example/header/normal.vue
> update for fix doc guide/menu example style error

- components/common/CHANGELOG.md
- components/common/package.json
- components/common/src/components/nv-cascaderSelect/cascaderSelect.vue
- components/common/src/components/nv-cascaderSelect/caspanel.vue
fix nv-cascaderSelect file loader
> fix nv-cascaderSelect file loader

- components/common/CHANGELOG.md
- components/common/demo/components/nvdutytable/nvdutytable.vue
- components/common/package.json
- components/common/src/assets/css/components/dutyTable.less
- components/common/src/components/nv-dutytable/CONSTANTS.js
- components/common/src/components/nv-dutytable/date-picker.js
- components/common/src/components/nv-dutytable/dutyTable.vue
feat(component): NvDutyTable support custom configuration of working days and sections
> feat(component): NvDutyTable support custom configuration of working days and sections

- doc/src/doc/component/transfer/transfer.md
docs:update Transfer component doc
> docs:update Transfer component doc

- components/common/test/unit/specs/nvDatePicker.spec.js
test: update unit test for NvDatePicker component
> test: update unit test for NvDatePicker component

- packages/noahv-core/lib/router.js
- packages/noahv-core/package.json
> feat(core): add entry and redirect conf for children router

- packages/noahv-i18n/lib/index.js
feat: add Timezone for noahv-i18n
> feat: add Timezone for noahv-i18n

- packages/noahv-i18n/package.json
fix: update noahv-i18n version
> fix: update noahv-i18n version

- doc/src/doc/visualComponent/eventriver.md
change the eventriver docschange the eventriver docs
> docs: change the eventriver docs

- doc/src/doc/visualComponent/eventriver.md
- tools/noahv-cli/bin/noahv-start
- tools/noahv-cli/package.json
> fix: change the noahv cli help text

- doc/src/doc/component/tree/tree.md
docs(doc): update tree component document
> docs(doc): update tree component document

- components/common/src/components/nv-chart/trend.vue
polish(components):优化保留小数位数为两位
> polish(components):优化保留小数位数为两位

- packages/noahv-request/README.md
- packages/noahv-request/lib/index.js
- packages/noahv-request/package.json
> feat(request): add the request config

- travis.sh
fix(ci/cd): fix test script config in travis
> fix(ci/cd): fix test script config in travis

- components/common/package.json
- components/common/src/components/nv-tree/tree.vue
> fix(tree): tree组件,解决重复点击问题

- components/visual/src/assets/css/billboard/billboard.less
- components/visual/src/mdtrend.vue
> fix:修复趋势图/billboard

- components/common/src/components/nv-chart/trend.vue
1. add error-tip slot for nv-trend
2. add no-data-tip slot, while also supports the old noDataTip prop, for nv-trend
> feat(component): add error-tip slot and no-data-tip slot for nv-trend

- components/common/src/components/nv-multiSelect/multiSelect.vue
1. 给nv-multiselect组件加入allByResultList参数。allByResultList=true的时候，点击全选的checkbox会从经过用户输入过滤的resultList中取数据。
> feat(component): 给nv-multiselect组件加入allByResultList参数

- components/common/src/components/nv-chart/trend.vue
> fix: 允许用户传入趋势图的点

- components/common/src/components/nv-chart/chartUtil.js
> fix: 修复浏览器怪异模式获取body节点的bug
